site_name: SciOp
repo_url: https://codeberg.org/sneakers-the-rat/sciop
repo_name: Codeberg
edit_uri: _edit/main/docs/
site_description: ''
site_author: ''
copyright: CC BY-NC-SA 4.0

nav:
  - Intro:
    - intro/overview.md
    - intro/roadmap.md
  - Using:
    - using/browsing.md
    - using/seeding.md
    - using/rss.md
    - using/moderation.md
    - using/curating.md
    - using/metadata.md
  - Uploading:
    - uploading/rules.md
    - uploading/formatting.md
    - uploading/torrents.md
    - uploading/checksums.md
    - uploading/trackers.md
  - Scraper's Guide:
    - scraping/web.md
    - scraping/http.md
    - scraping/s3.md
    - scraping/ftp.md
  - privacy.md
  - API: /docs/api
  - API Examples:
    - examples/uploading.md
  - Developing:
    - develop/design.md
    - develop/contributing.md
    - develop/frontend.md
    - develop/backend.md
    - develop/error_handling.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.path
    - content.code.copy


# this will get overridden by {config.public_url} + '/docs/'
# when built by the app
site_url: https://sciop.net/docs/

markdown_extensions:
  - pymdownx.snippets:
      base_path: ["docs/"]



