site_name: The Sci Op !
repo_url: https://codeberg.org/Safeguarding/sciop
repo_name: Codeberg
edit_uri: _edit/main/docs/
site_description: ''
site_author: ''
copyright: CC BY-NC-SA 4.0

nav:
  - index.md
  - Intro:
      - intro/overview.md
      - intro/roadmap.md
      - intro/bittorrent.md
  - Using Sciop:
      - using/index.md
      - using/browsing.md
      - using/torrenting.md
      - using/rss.md
      - using/moderation.md
      - using/curating.md
      - using/metadata.md
  - Uploading:
      - uploading/index.md
      - uploading/rules.md
      - uploading/formatting.md
      - uploading/torrents.md
      - uploading/checksums.md
      - uploading/trackers.md
  - Scraper's Guide:
      - scraping/index.md
      - scraping/webpages.md
      - scraping/s3.md
      - scraping/ftp.md
  - privacy.md
  - API: /docs/api
  - API Examples:
      - examples/index.md
      - examples/uploading.md
  - Running:
      - running/index.md
      - running/maintenance.md
  - Developers:
      - develop/index.md
      - develop/design.md
      - develop/contributing.md
      - develop/frontend.md
      - develop/backend.md
      - develop/error_handling.md
      - develop/jobs.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: sciop-dark
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: sciop-light
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.path
    - toc.integrate
    - content.code.copy

extra_css:
  - css/fonts.css
  - css/vars.css
  - css/theme.css


# this will get overridden by {config.public_url} + '/docs/'
# when built by the app
site_url: https://sciop.net/docs/

markdown_extensions:
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets:
      base_path: ["docs/"]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
- redirects:
    redirect_maps:
      "using/seeding.md": "using/torrenting.md"

