site_name: The Sci Op !
repo_url: https://codeberg.org/Safeguarding/sciop
repo_name: Codeberg
edit_uri: _edit/main/docs/
site_description: ''
site_author: ''
copyright: CC BY-NC-SA 4.0

nav:
  - index.md
  - quickstart.md
  - Intro:
      - intro/overview.md
      - intro/bittorrent.md
      - intro/bittorrent_v2.md
      - intro/roadmap.md
  - Using Sciop:
      - using/index.md
      - using/browsing.md
      - using/torrenting.md
      - using/rss.md
      - using/moderation.md
      - using/curating.md
      - using/metadata.md
  - Uploading:
      - uploading/index.md
      - uploading/rules.md
      - uploading/formatting.md
      - uploading/torrents.md
      - uploading/checksums.md
      - uploading/trackers.md
  - Scraper's Guide:
      - scraping/index.md
      - scraping/webpages.md
      - scraping/s3.md
      - scraping/ftp.md
      - scraping/github.md
  - privacy.md
  - API: /docs/api
  - Python API:
      - python/index.md
      - python/config.md
      - Models:
          - python/models/index.md
          - python/models/base.md
          - python/models/account.md
          - python/models/api.md
          - python/models/dataset.md
          - python/models/moderation.md
          - python/models/rss.md
          - python/models/stats.md
          - python/models/system.md
          - python/models/tag.md
          - python/models/torrent.md
          - python/models/tracker.md
          - python/models/upload.md
      - python/mixins.md
      - python/types.md
      - python/deps.md
      - python/middleware.md
      - python/services.md
      - python/db.md
      - python/crud.md
      - python/logging.md
      - python/scheduler.md
      - python/exceptions.md
  - API Examples:
      - examples/index.md
      - examples/uploading.md
  - Running:
      - running/index.md
      - running/cli.md
      - running/maintenance.md
  - Developers:
      - develop/index.md
      - develop/design.md
      - develop/contributing.md
      - develop/debugging.md
      - develop/frontend.md
      - develop/backend.md
      - develop/error_handling.md
      - develop/jobs.md
  - changelog.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: sciop-dark
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: sciop-light
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.path
    - toc.integrate

extra_css:
  - css/fonts.css
  - css/vars.css
  - css/theme.css


# this will get overridden by {config.server.base_url} + '/docs/'
# when built by the app
site_url: https://sciop.net/docs/
extra:
 homepage: /
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - mkdocs-click
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      base_path: ["docs/"]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true

plugins:
  - autorefs
  - git-authors:
      enabled: true
      show_email_address: false
  - macros
  - mermaid2
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
          options:
            backlinks: tree
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            docstring_style: google
            heading_level: 2
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_if_no_docstring: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            filters:
              - "!^_[^_]"
              - "!fts_.*"
              - "!count_statement"
              - "!primary_key_column"
              - "!after_create"
              - "!register_events"
              - "!get_versions"
              - "!history_table"
              - "!editable_objects"
              - "!__history_meta_cols__"
              - "!rebuild_history_models"
            extensions:
              - griffe_fieldz:
                  include_inherited: true
              - griffe_inherited_docstrings
  - redirects:
      redirect_maps:
        "using/seeding.md": "using/torrenting.md"
  - search

