name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-solaris:
    name: tests-python${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Echo github server url
        run: |
          echo "${{ env.GITHUB_SERVER_URL }}"
      - name: Install python
        uses: https://code.forgejo.org/actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install deps
        run: pip install -e .[test]
      - name: Run tests
        run: |
          mkdir $HOME/tmp
          pytest -m "not playwright"

  test-playwright:
    name: tests-playwright-python${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Echo github server url
        run: |
          echo "${{ env.GITHUB_SERVER_URL }}"
      - name: Install python
        uses: https://code.forgejo.org/actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install deps
        run: pip install -e .[test]
      - name: Install firefox
#        run: playwright install firefox
        run: |
          playwright install-deps
          playwright install firefox
      - name: Run tests
        run: |
          mkdir $HOME/tmp
          pytest -m "playwright"

  test-slow:
    name: tests-slow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Install python
        uses: https://code.forgejo.org/actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: 'pip'
      - name: Install deps
        run: pip install -e .[test]
      - name: Run tests
        run: |
          mkdir $HOME/tmp
          pytest --with-slow -m "slow"