"""support_v2_only

Revision ID: efb45cd6cac9
Revises: 246b20d19ea1
Create Date: 2025-07-28 05:55:38.772679+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efb45cd6cac9"
down_revision: Union[str, None] = "246b20d19ea1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("torrent_files", schema=None) as batch_op:
        batch_op.alter_column("v1_infohash", existing_type=sa.VARCHAR(length=40), nullable=True)

    with op.batch_alter_table("torrent_files__history", schema=None) as batch_op:
        batch_op.alter_column(
            "v1_infohash", existing_type=sa.VARCHAR(length=40), nullable=True, autoincrement=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("torrent_files__history", schema=None) as batch_op:
        batch_op.alter_column(
            "v1_infohash", existing_type=sa.VARCHAR(length=40), nullable=False, autoincrement=False
        )

    with op.batch_alter_table("torrent_files", schema=None) as batch_op:
        batch_op.alter_column("v1_infohash", existing_type=sa.VARCHAR(length=40), nullable=False)

    # ### end Alembic commands ###
