"""create_time index

Revision ID: 0f06a275f152
Revises: 0f29b9ed0f9d
Create Date: 2025-05-26 17:37:02.187948+00:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f06a275f152"
down_revision: Union[str, None] = "0f29b9ed0f9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_datasets_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("datasets__history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_datasets__history_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("hitcount", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_hitcount_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_uploads_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("uploads__history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_uploads__history_created_at"), ["created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploads__history_created_at"))

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploads_created_at"))

    with op.batch_alter_table("hitcount", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hitcount_created_at"))

    with op.batch_alter_table("datasets__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_datasets__history_created_at"))

    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_datasets_created_at"))

    # ### end Alembic commands ###
