"""add-no-response-error

Revision ID: 9cd226ce1166
Revises: 8c660f76bc3e
Create Date: 2025-04-08 01:30:38.748428+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cd226ce1166"
down_revision: Union[str, None] = "8c660f76bc3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trackers", schema=None) as batch_op:
        batch_op.alter_column(
            "error_type",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Enum(
                "dns",
                "connection",
                "timeout",
                "unpack",
                "protocol",
                "no_response",
                "default",
                name="scrapeerrortype",
            ),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trackers", schema=None) as batch_op:
        batch_op.alter_column(
            "error_type",
            existing_type=sa.Enum(
                "dns",
                "connection",
                "timeout",
                "unpack",
                "protocol",
                "no_response",
                "default",
                name="scrapeerrortype",
            ),
            type_=sa.VARCHAR(length=10),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
