"""drop-file-in-torrent-history

Revision ID: e5376c65e837
Revises: 3e34a3487cb2
Create Date: 2025-03-28 23:47:21.118651+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5376c65e837"
down_revision: Union[str, None] = "3e34a3487cb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files_in_torrent__history", schema=None) as batch_op:
        batch_op.drop_index("ix_files_in_torrent__history_file_in_torrent_id")
        batch_op.drop_index("ix_files_in_torrent__history_torrent_id")

    op.drop_table("files_in_torrent__history")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files_in_torrent__history",
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("file_in_torrent_id", sa.INTEGER(), nullable=False),
        sa.Column("path", sa.VARCHAR(length=1024), nullable=False),
        sa.Column("size", sa.INTEGER(), nullable=False),
        sa.Column("torrent_id", sa.INTEGER(), nullable=True),
        sa.Column(
            "version_created_at",
            sa.DATETIME(),
            server_default=sa.text("(datetime('now', 'utc', 'subsec'))"),
            nullable=False,
        ),
        sa.Column("version_comment", sa.TEXT(length=4096), nullable=True),
        sa.Column("version_created_by", sa.INTEGER(), nullable=True),
        sa.Column("version_is_deletion", sa.BOOLEAN(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_in_torrent_id"],
            ["files_in_torrent.file_in_torrent_id"],
            name="fk_files_in_torrent__history_file_in_torrent_id_files_in_torrent",
        ),
        sa.ForeignKeyConstraint(
            ["torrent_id"],
            ["torrent_files.torrent_file_id"],
            name="fk_files_in_torrent_torrent_id_torrent_files",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_created_by"],
            ["accounts.account_id"],
            name="fk_files_in_torrent__history_version_created_by_accounts",
        ),
        sa.PrimaryKeyConstraint(
            "file_in_torrent_id",
            "version_created_at",
            name="pk_files_in_torrent__history_file_in_torrent_id_version_created_at",
        ),
    )
    with op.batch_alter_table("files_in_torrent__history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_files_in_torrent__history_torrent_id", ["torrent_id"], unique=False
        )
        batch_op.create_index(
            "ix_files_in_torrent__history_file_in_torrent_id", ["file_in_torrent_id"], unique=False
        )

    # ### end Alembic commands ###
