"""add-report-resolved-at

Revision ID: 8b8cc412507a
Revises: b98157bb48bd
Create Date: 2025-10-17 06:52:35.957632+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b8cc412507a"
down_revision: Union[str, None] = "b98157bb48bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("resolved_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_column("resolved_at")

    # ### end Alembic commands ###
