"""update-moderation-action

Revision ID: 15c347585316
Revises: b81af74dcf0d
Create Date: 2025-10-20 22:11:30.250308+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15c347585316"
down_revision: Union[str, None] = "b81af74dcf0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.alter_column(
            "action",
            existing_type=sa.VARCHAR(length=12),
            type_=sa.Enum(
                "request",
                "approve",
                "unapprove",
                "deny",
                "report",
                "add_scope",
                "remove_scope",
                "dismiss",
                "trust",
                "distrust",
                "suspend",
                "suspend_remove",
                "restore",
                "remove",
                "hide",
                name="moderationaction",
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.alter_column(
            "action",
            existing_type=sa.Enum(
                "request",
                "approve",
                "unapprove",
                "deny",
                "report",
                "add_scope",
                "remove_scope",
                "dismiss",
                "trust",
                "distrust",
                "suspend",
                "suspend_remove",
                "restore",
                "remove",
                "hide",
                name="moderationaction",
            ),
            type_=sa.VARCHAR(length=12),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
