"""add-bittorent-source-type

Revision ID: a62f6bbf15de
Revises: 83e6a7fad77f
Create Date: 2025-03-27 02:48:16.468887+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a62f6bbf15de"
down_revision: Union[str, None] = "83e6a7fad77f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.alter_column(
            "source_type",
            existing_type=sa.VARCHAR(length=7),
            type_=sa.Enum("unknown", "web", "http", "ftp", "s3", "bittorrent", name="sourcetype"),
            existing_nullable=False,
        )

    with op.batch_alter_table("datasets__history", schema=None) as batch_op:
        batch_op.alter_column(
            "source_type",
            existing_type=sa.VARCHAR(length=7),
            type_=sa.Enum("unknown", "web", "http", "ftp", "s3", "bittorrent", name="sourcetype"),
            existing_nullable=False,
            autoincrement=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasets__history", schema=None) as batch_op:
        batch_op.alter_column(
            "source_type",
            existing_type=sa.Enum(
                "unknown", "web", "http", "ftp", "s3", "bittorrent", name="sourcetype"
            ),
            type_=sa.VARCHAR(length=7),
            existing_nullable=False,
            autoincrement=False,
        )

    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.alter_column(
            "source_type",
            existing_type=sa.Enum(
                "unknown", "web", "http", "ftp", "s3", "bittorrent", name="sourcetype"
            ),
            type_=sa.VARCHAR(length=7),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
