"""add_atom_feeds

Revision ID: d7d6663f05f7
Revises: 6aeff935f1c3
Create Date: 2025-09-03 00:33:30.427820+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7d6663f05f7"
down_revision: Union[str, None] = "6aeff935f1c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "atom_feeds",
        sa.Column("atom_feed_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("atom_feed_id", name=op.f("pk_atom_feeds_atom_feed_id")),
    )
    op.create_table(
        "atom_feed_entries",
        sa.Column("feed_id", sa.Integer(), nullable=True),
        sa.Column("atom_entry_id", sa.Integer(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(length=8192), nullable=False),
        sa.Column("link", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("author_name", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
        sa.Column("author_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published", sa.DateTime(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["atom_feeds.atom_feed_id"],
            name=op.f("fk_atom_feed_entries_feed_id_atom_feeds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("atom_entry_id", name=op.f("pk_atom_feed_entries_atom_entry_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("atom_feed_entries")
    op.drop_table("atom_feeds")
    # ### end Alembic commands ###
