"""add_webseed_moderation

Revision ID: f8181163141d
Revises: 6aeff935f1c3
Create Date: 2025-08-12 07:27:29.858216+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8181163141d"
down_revision: Union[str, None] = "6aeff935f1c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.add_column(sa.Column("target_webseed_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_audit_log_target_webseed_id"), ["target_webseed_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_audit_log_target_webseed_id_webseeds"),
            "webseeds",
            ["target_webseed_id"],
            ["webseed_id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("webseeds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_approved", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("is_removed", sa.Boolean(), nullable=False))
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=11),
            type_=sa.Enum(
                "in_original",
                "pending_review",
                "queued",
                "in_progress",
                "validated",
                "error",
                name="webseedstatus",
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webseeds", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "in_original",
                "pending_review",
                "queued",
                "in_progress",
                "validated",
                "error",
                name="webseedstatus",
            ),
            type_=sa.VARCHAR(length=11),
            existing_nullable=False,
        )
        batch_op.drop_column("is_removed")
        batch_op.drop_column("is_approved")

    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_audit_log_target_webseed_id_webseeds"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_audit_log_target_webseed_id"))
        batch_op.drop_column("target_webseed_id")

    # ### end Alembic commands ###
