"""remove-padfiles

Revision ID: f65409701c98
Revises: 9cd226ce1166
Create Date: 2025-04-08 06:10:56.976308+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f65409701c98"
down_revision: Union[str, None] = "9cd226ce1166"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    table = sa.Table(
        "files_in_torrent",
        sa.MetaData(),
        sa.Column("path", sa.String(), key="path"),
    )
    stmt = sa.delete(table).where(table.c.path.like("%/.pad/%"))
    conn = op.get_bind()
    conn.execute(stmt)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
