"""create_time index

Revision ID: 757be3a7198d
Revises: 0f29b9ed0f9d
Create Date: 2025-05-26 17:05:35.425404+00:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "757be3a7198d"
down_revision: Union[str, None] = "0f29b9ed0f9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account_scope_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_account_scope_links_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_accounts_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("dataset_parts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_parts_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("dataset_parts__history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_parts__history_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("dataset_paths", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_paths_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("dataset_paths__history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_paths__history_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("dataset_tag_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_tag_links_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("dataset_tag_links__history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_tag_links__history_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_datasets_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("datasets__history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_datasets__history_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("external_identifiers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_external_identifiers_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("external_identifiers__history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_external_identifiers__history_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("external_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_external_sources_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("external_sources__history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_external_sources__history_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("files_in_torrent", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_files_in_torrent_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("scopes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scopes_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("site_stats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_site_stats_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("torrent_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_torrent_files_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("torrent_files__history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_torrent_files__history_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("torrent_tracker_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_torrent_tracker_links_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("trackers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trackers_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_uploads_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("uploads__history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_uploads__history_created_at"), ["created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploads__history_created_at"))

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploads_created_at"))

    with op.batch_alter_table("trackers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trackers_created_at"))

    with op.batch_alter_table("torrent_tracker_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_torrent_tracker_links_created_at"))

    with op.batch_alter_table("torrent_files__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_torrent_files__history_created_at"))

    with op.batch_alter_table("torrent_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_torrent_files_created_at"))

    with op.batch_alter_table("site_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_site_stats_created_at"))

    with op.batch_alter_table("scopes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scopes_created_at"))

    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_created_at"))

    with op.batch_alter_table("files_in_torrent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_files_in_torrent_created_at"))

    with op.batch_alter_table("external_sources__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_sources__history_created_at"))

    with op.batch_alter_table("external_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_sources_created_at"))

    with op.batch_alter_table("external_identifiers__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_identifiers__history_created_at"))

    with op.batch_alter_table("external_identifiers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_identifiers_created_at"))

    with op.batch_alter_table("datasets__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_datasets__history_created_at"))

    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_datasets_created_at"))

    with op.batch_alter_table("dataset_tag_links__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_tag_links__history_created_at"))

    with op.batch_alter_table("dataset_tag_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_tag_links_created_at"))

    with op.batch_alter_table("dataset_paths__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_paths__history_created_at"))

    with op.batch_alter_table("dataset_paths", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_paths_created_at"))

    with op.batch_alter_table("dataset_parts__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_parts__history_created_at"))

    with op.batch_alter_table("dataset_parts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_parts_created_at"))

    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_created_at"))

    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_created_at"))

    with op.batch_alter_table("account_scope_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_scope_links_created_at"))

    # ### end Alembic commands ###
