"""hit-counter

Revision ID: 82afde6fd25b
Revises: 0f0198cd54b8
Create Date: 2025-05-05 08:27:29.758979+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82afde6fd25b"
down_revision: Union[str, None] = "0f0198cd54b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hitcount",
        sa.Column("hit_count_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("hit_count_id", name=op.f("pk_hitcount_hit_count_id")),
    )
    with op.batch_alter_table("hitcount", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_hitcount_path"), ["path"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hitcount", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hitcount_path"))

    op.drop_table("hitcount")
    # ### end Alembic commands ###
