"""bump-limits

Revision ID: 0f0198cd54b8
Revises: f65409701c98
Create Date: 2025-04-19 09:36:25.348248+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f0198cd54b8"
down_revision: Union[str, None] = "f65409701c98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.VARCHAR(length=16384),
            type_=sqlmodel.sql.sqltypes.AutoString(length=163840),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description_html",
            existing_type=sa.VARCHAR(length=32768),
            type_=sqlmodel.sql.sqltypes.AutoString(length=655360),
            existing_nullable=True,
        )

    with op.batch_alter_table("datasets__history", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.VARCHAR(length=16384),
            type_=sqlmodel.sql.sqltypes.AutoString(length=163840),
            existing_nullable=True,
            autoincrement=False,
        )
        batch_op.alter_column(
            "description_html",
            existing_type=sa.VARCHAR(length=32768),
            type_=sqlmodel.sql.sqltypes.AutoString(length=655360),
            existing_nullable=True,
            autoincrement=False,
        )

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.alter_column(
            "method",
            existing_type=sa.VARCHAR(length=8192),
            type_=sqlmodel.sql.sqltypes.AutoString(length=163840),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "method_html",
            existing_type=sa.VARCHAR(length=16384),
            type_=sqlmodel.sql.sqltypes.AutoString(length=655360),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.VARCHAR(length=8192),
            type_=sqlmodel.sql.sqltypes.AutoString(length=163840),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description_html",
            existing_type=sa.VARCHAR(length=16384),
            type_=sqlmodel.sql.sqltypes.AutoString(length=655360),
            existing_nullable=True,
        )

    with op.batch_alter_table("uploads__history", schema=None) as batch_op:
        batch_op.alter_column(
            "method",
            existing_type=sa.VARCHAR(length=8192),
            type_=sqlmodel.sql.sqltypes.AutoString(length=163840),
            existing_nullable=True,
            autoincrement=False,
        )
        batch_op.alter_column(
            "method_html",
            existing_type=sa.VARCHAR(length=16384),
            type_=sqlmodel.sql.sqltypes.AutoString(length=655360),
            existing_nullable=True,
            autoincrement=False,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.VARCHAR(length=8192),
            type_=sqlmodel.sql.sqltypes.AutoString(length=163840),
            existing_nullable=True,
            autoincrement=False,
        )
        batch_op.alter_column(
            "description_html",
            existing_type=sa.VARCHAR(length=16384),
            type_=sqlmodel.sql.sqltypes.AutoString(length=655360),
            existing_nullable=True,
            autoincrement=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads__history", schema=None) as batch_op:
        batch_op.alter_column(
            "description_html",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=655360),
            type_=sa.VARCHAR(length=16384),
            existing_nullable=True,
            autoincrement=False,
        )
        batch_op.alter_column(
            "description",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=163840),
            type_=sa.VARCHAR(length=8192),
            existing_nullable=True,
            autoincrement=False,
        )
        batch_op.alter_column(
            "method_html",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=655360),
            type_=sa.VARCHAR(length=16384),
            existing_nullable=True,
            autoincrement=False,
        )
        batch_op.alter_column(
            "method",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=163840),
            type_=sa.VARCHAR(length=8192),
            existing_nullable=True,
            autoincrement=False,
        )

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.alter_column(
            "description_html",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=655360),
            type_=sa.VARCHAR(length=16384),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=163840),
            type_=sa.VARCHAR(length=8192),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "method_html",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=655360),
            type_=sa.VARCHAR(length=16384),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "method",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=163840),
            type_=sa.VARCHAR(length=8192),
            existing_nullable=True,
        )

    with op.batch_alter_table("datasets__history", schema=None) as batch_op:
        batch_op.alter_column(
            "description_html",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=655360),
            type_=sa.VARCHAR(length=32768),
            existing_nullable=True,
            autoincrement=False,
        )
        batch_op.alter_column(
            "description",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=163840),
            type_=sa.VARCHAR(length=16384),
            existing_nullable=True,
            autoincrement=False,
        )

    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.alter_column(
            "description_html",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=655360),
            type_=sa.VARCHAR(length=32768),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=163840),
            type_=sa.VARCHAR(length=16384),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
