"""add-fk-indices

Revision ID: de2fc8d71cd3
Revises: a62f6bbf15de
Create Date: 2025-03-27 04:22:40.203138+00:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de2fc8d71cd3"
down_revision: Union[str, None] = "a62f6bbf15de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account_scope_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_account_scope_links_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_account_scope_links_scope_id"), ["scope_id"], unique=False
        )

    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_log_target_account_id"), ["target_account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_target_dataset_id"), ["target_dataset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_target_dataset_part_id"),
            ["target_dataset_part_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_target_upload_id"), ["target_upload_id"], unique=False
        )

    with op.batch_alter_table("dataset_parts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_parts_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dataset_parts_dataset_id"), ["dataset_id"], unique=False
        )

    with op.batch_alter_table("dataset_parts__history", schema=None) as batch_op:
        batch_op.drop_index("ix_dataset_parts__history_part_slug_history")
        batch_op.create_index("ix_dataset_parts__history_account_id", ["account_id"], unique=False)
        batch_op.create_index("ix_dataset_parts__history_dataset_id", ["dataset_id"], unique=False)
        batch_op.create_index(
            "ix_dataset_parts__history_dataset_part_id", ["dataset_part_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dataset_parts__history_part_slug"), ["part_slug"], unique=False
        )

    with op.batch_alter_table("dataset_paths", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_paths_dataset_part_id"), ["dataset_part_id"], unique=False
        )

    with op.batch_alter_table("dataset_paths__history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_dataset_paths__history_dataset_part_id", ["dataset_part_id"], unique=False
        )
        batch_op.create_index(
            "ix_dataset_paths__history_dataset_path_id", ["dataset_path_id"], unique=False
        )

    with op.batch_alter_table("dataset_tag_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_tag_links_dataset_id"), ["dataset_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_dataset_tag_links_tag_id"), ["tag_id"], unique=False)

    with op.batch_alter_table("dataset_tag_links__history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_dataset_tag_links__history_dataset_id", ["dataset_id"], unique=False
        )
        batch_op.create_index("ix_dataset_tag_links__history_tag_id", ["tag_id"], unique=False)

    with op.batch_alter_table("dataset_urls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_urls_dataset_id"), ["dataset_id"], unique=False
        )

    with op.batch_alter_table("dataset_urls__history", schema=None) as batch_op:
        batch_op.create_index("ix_dataset_urls__history_dataset_id", ["dataset_id"], unique=False)
        batch_op.create_index(
            "ix_dataset_urls__history_dataset_url_id", ["dataset_url_id"], unique=False
        )

    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_datasets_account_id"), ["account_id"], unique=False)

    with op.batch_alter_table("datasets__history", schema=None) as batch_op:
        batch_op.drop_index("ix_datasets__history_slug_history")
        batch_op.create_index("ix_datasets__history_account_id", ["account_id"], unique=False)
        batch_op.create_index("ix_datasets__history_dataset_id", ["dataset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_datasets__history_slug"), ["slug"], unique=False)

    with op.batch_alter_table("external_identifiers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_external_identifiers_dataset_id"), ["dataset_id"], unique=False
        )

    with op.batch_alter_table("external_identifiers__history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_external_identifiers__history_dataset_id", ["dataset_id"], unique=False
        )
        batch_op.create_index(
            "ix_external_identifiers__history_external_identifier_id",
            ["external_identifier_id"],
            unique=False,
        )

    with op.batch_alter_table("external_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_external_sources_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_external_sources_dataset_id"), ["dataset_id"], unique=False
        )

    with op.batch_alter_table("external_sources__history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_external_sources__history_account_id", ["account_id"], unique=False
        )
        batch_op.create_index(
            "ix_external_sources__history_dataset_id", ["dataset_id"], unique=False
        )
        batch_op.create_index(
            "ix_external_sources__history_external_source_id", ["external_source_id"], unique=False
        )

    with op.batch_alter_table("files_in_torrent", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_files_in_torrent_torrent_id"), ["torrent_id"], unique=False
        )

    with op.batch_alter_table("files_in_torrent__history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_files_in_torrent__history_file_in_torrent_id", ["file_in_torrent_id"], unique=False
        )
        batch_op.create_index(
            "ix_files_in_torrent__history_torrent_id", ["torrent_id"], unique=False
        )

    with op.batch_alter_table("torrent_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_torrent_files_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_torrent_files_upload_id"), ["upload_id"], unique=False)

    with op.batch_alter_table("torrent_files__history", schema=None) as batch_op:
        batch_op.drop_index("ix_torrent_files__history_short_hash_history")
        batch_op.drop_index("ix_torrent_files__history_v1_infohash_history")
        batch_op.drop_index("ix_torrent_files__history_v2_infohash_history")
        batch_op.create_index("ix_torrent_files__history_account_id", ["account_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_torrent_files__history_short_hash"), ["short_hash"], unique=False
        )
        batch_op.create_index(
            "ix_torrent_files__history_torrent_file_id", ["torrent_file_id"], unique=False
        )
        batch_op.create_index("ix_torrent_files__history_upload_id", ["upload_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_torrent_files__history_v1_infohash"), ["v1_infohash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_torrent_files__history_v2_infohash"), ["v2_infohash"], unique=False
        )

    with op.batch_alter_table("torrent_tracker_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_torrent_tracker_links_torrent_file_id"),
            ["torrent_file_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_torrent_tracker_links_tracker_id"), ["tracker_id"], unique=False
        )

    with op.batch_alter_table("upload_dataset_part_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_upload_dataset_part_links_dataset_part_id"),
            ["dataset_part_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_upload_dataset_part_links_upload_id"), ["upload_id"], unique=False
        )

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_uploads_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_uploads_dataset_id"), ["dataset_id"], unique=False)

    with op.batch_alter_table("uploads__history", schema=None) as batch_op:
        batch_op.create_index("ix_uploads__history_account_id", ["account_id"], unique=False)
        batch_op.create_index("ix_uploads__history_dataset_id", ["dataset_id"], unique=False)
        batch_op.create_index("ix_uploads__history_upload_id", ["upload_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads__history", schema=None) as batch_op:
        batch_op.drop_index("ix_uploads__history_upload_id")
        batch_op.drop_index("ix_uploads__history_dataset_id")
        batch_op.drop_index("ix_uploads__history_account_id")

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploads_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_uploads_account_id"))

    with op.batch_alter_table("upload_dataset_part_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_upload_dataset_part_links_upload_id"))
        batch_op.drop_index(batch_op.f("ix_upload_dataset_part_links_dataset_part_id"))

    with op.batch_alter_table("torrent_tracker_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_torrent_tracker_links_tracker_id"))
        batch_op.drop_index(batch_op.f("ix_torrent_tracker_links_torrent_file_id"))

    with op.batch_alter_table("torrent_files__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_torrent_files__history_v2_infohash"))
        batch_op.drop_index(batch_op.f("ix_torrent_files__history_v1_infohash"))
        batch_op.drop_index("ix_torrent_files__history_upload_id")
        batch_op.drop_index("ix_torrent_files__history_torrent_file_id")
        batch_op.drop_index(batch_op.f("ix_torrent_files__history_short_hash"))
        batch_op.drop_index("ix_torrent_files__history_account_id")
        batch_op.create_index(
            "ix_torrent_files__history_v2_infohash_history", ["v2_infohash"], unique=False
        )
        batch_op.create_index(
            "ix_torrent_files__history_v1_infohash_history", ["v1_infohash"], unique=False
        )
        batch_op.create_index(
            "ix_torrent_files__history_short_hash_history", ["short_hash"], unique=False
        )

    with op.batch_alter_table("torrent_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_torrent_files_upload_id"))
        batch_op.drop_index(batch_op.f("ix_torrent_files_account_id"))

    with op.batch_alter_table("files_in_torrent__history", schema=None) as batch_op:
        batch_op.drop_index("ix_files_in_torrent__history_torrent_id")
        batch_op.drop_index("ix_files_in_torrent__history_file_in_torrent_id")

    with op.batch_alter_table("files_in_torrent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_files_in_torrent_torrent_id"))

    with op.batch_alter_table("external_sources__history", schema=None) as batch_op:
        batch_op.drop_index("ix_external_sources__history_external_source_id")
        batch_op.drop_index("ix_external_sources__history_dataset_id")
        batch_op.drop_index("ix_external_sources__history_account_id")

    with op.batch_alter_table("external_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_sources_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_external_sources_account_id"))

    with op.batch_alter_table("external_identifiers__history", schema=None) as batch_op:
        batch_op.drop_index("ix_external_identifiers__history_external_identifier_id")
        batch_op.drop_index("ix_external_identifiers__history_dataset_id")

    with op.batch_alter_table("external_identifiers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_identifiers_dataset_id"))

    with op.batch_alter_table("datasets__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_datasets__history_slug"))
        batch_op.drop_index("ix_datasets__history_dataset_id")
        batch_op.drop_index("ix_datasets__history_account_id")
        batch_op.create_index("ix_datasets__history_slug_history", ["slug"], unique=False)

    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_datasets_account_id"))

    with op.batch_alter_table("dataset_urls__history", schema=None) as batch_op:
        batch_op.drop_index("ix_dataset_urls__history_dataset_url_id")
        batch_op.drop_index("ix_dataset_urls__history_dataset_id")

    with op.batch_alter_table("dataset_urls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_urls_dataset_id"))

    with op.batch_alter_table("dataset_tag_links__history", schema=None) as batch_op:
        batch_op.drop_index("ix_dataset_tag_links__history_tag_id")
        batch_op.drop_index("ix_dataset_tag_links__history_dataset_id")

    with op.batch_alter_table("dataset_tag_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_tag_links_tag_id"))
        batch_op.drop_index(batch_op.f("ix_dataset_tag_links_dataset_id"))

    with op.batch_alter_table("dataset_paths__history", schema=None) as batch_op:
        batch_op.drop_index("ix_dataset_paths__history_dataset_path_id")
        batch_op.drop_index("ix_dataset_paths__history_dataset_part_id")

    with op.batch_alter_table("dataset_paths", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_paths_dataset_part_id"))

    with op.batch_alter_table("dataset_parts__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_parts__history_part_slug"))
        batch_op.drop_index("ix_dataset_parts__history_dataset_part_id")
        batch_op.drop_index("ix_dataset_parts__history_dataset_id")
        batch_op.drop_index("ix_dataset_parts__history_account_id")
        batch_op.create_index(
            "ix_dataset_parts__history_part_slug_history", ["part_slug"], unique=False
        )

    with op.batch_alter_table("dataset_parts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_parts_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_dataset_parts_account_id"))

    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_target_upload_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_target_dataset_part_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_target_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_target_account_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_actor_id"))

    with op.batch_alter_table("account_scope_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_scope_links_scope_id"))
        batch_op.drop_index(batch_op.f("ix_account_scope_links_account_id"))

    # ### end Alembic commands ###
