"""username-collate-nocase

Revision ID: 3e34a3487cb2
Revises: de2fc8d71cd3
Create Date: 2025-03-28 09:43:32.107416+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e34a3487cb2"
down_revision: Union[str, None] = "de2fc8d71cd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.alter_column(
            "username",
            type_=sa.VARCHAR(length=64, collation="NOCASE"),
            unique=True,
            index=True,
            existing_type=sa.VARCHAR(length=64),
            nullable=False,
        )
        batch_op.create_unique_constraint("uq_accounts_username", ["username"])
        batch_op.create_index(batch_op.f("ix_accounts_username"), ["username"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_username"))

    # ### end Alembic commands ###
