"""rm-file-in-torrent-timestamps

Revision ID: 99812ae0d9b1
Revises: d7d6663f05f7
Create Date: 2025-09-04 23:29:11.994919+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99812ae0d9b1"
down_revision: Union[str, None] = "d7d6663f05f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files_in_torrent", schema=None) as batch_op:
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files_in_torrent", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column("updated_at", sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
