"""report-action

Revision ID: b81af74dcf0d
Revises: 8b8cc412507a
Create Date: 2025-10-17 08:17:13.546267+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b81af74dcf0d"
down_revision: Union[str, None] = "8b8cc412507a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.alter_column(
            "action",
            existing_type=sa.VARCHAR(length=12),
            type_=sa.Enum(
                "dismiss", "hide", "remove", "suspend", "suspend_remove", name="reportaction"
            ),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.alter_column(
            "action",
            existing_type=sa.Enum(
                "dismiss", "hide", "remove", "suspend", "suspend_remove", name="reportaction"
            ),
            type_=sa.VARCHAR(length=12),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
