"""create-scope-links-table

Revision ID: 8eb0432e6bb0
Revises: 99812ae0d9b1
Create Date: 2026-01-14 03:02:12.181220+00:00

"""

from datetime import UTC, datetime
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8eb0432e6bb0"
down_revision: Union[str, None] = "99812ae0d9b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_scope_links",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("item_scope_link_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("dataset_id", sa.Integer(), nullable=True),
        sa.Column("scope_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
            name=op.f("fk_item_scope_links_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.dataset_id"],
            name=op.f("fk_item_scope_links_dataset_id_datasets"),
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"], ["scopes.scope_id"], name=op.f("fk_item_scope_links_scope_id_scopes")
        ),
        sa.PrimaryKeyConstraint(
            "item_scope_link_id", name=op.f("pk_item_scope_links_item_scope_link_id")
        ),
        sa.UniqueConstraint(
            "account_id", "dataset_id", "scope_id", name="_account_id_dataset_id_scope_id_uc"
        ),
    )
    with op.batch_alter_table("item_scope_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_item_scope_links_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_item_scope_links_dataset_id"), ["dataset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_item_scope_links_scope_id"), ["scope_id"], unique=False
        )

    with op.batch_alter_table("scopes", schema=None) as batch_op:
        batch_op.alter_column(
            "scope",
            existing_type=sa.VARCHAR(length=6),
            type_=sa.Enum(
                "submit",
                "upload",
                "review",
                "admin",
                "root",
                "edit",
                "permissions",
                "delete",
                name="scopes",
            ),
            existing_nullable=False,
        )

    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_datasets_account_id"))
        batch_op.drop_constraint(batch_op.f("fk_datasets_account_id_accounts"), type_="foreignkey")
        batch_op.drop_column("account_id")

    with op.batch_alter_table("datasets__history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_datasets__history_account_id"))
        batch_op.drop_constraint(batch_op.f("fk_datasets_account_id_accounts"), type_="foreignkey")
        batch_op.drop_column("account_id")

    now = datetime.now(UTC)
    new_scopes = [
        {"scope": "edit", "created_at": now, "updated_at": now},
        {"scope": "permissions", "created_at": now, "updated_at": now},
        {"scope": "delete", "created_at": now, "updated_at": now},
    ]

    conn = op.get_bind()
    Scopes = sa.Table("scopes", sa.MetaData(), autoload_with=conn)
    op.bulk_insert(Scopes, new_scopes)
    conn.execute(
        sa.text(
            """
            INSERT INTO item_scope_links (
               created_at, updated_at, scope_id, account_id, dataset_id
            )
            SELECT
               scopes.created_at,
               scopes.updated_at,
               scopes.scope_id,
               datasets.account_id,
               datasets.dataset_id
            FROM datasets
            JOIN scopes ON scopes.scope IN ("edit", "permissions", "delete")
            WHERE datasets.account_id IS NOT NULL
            """
        )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasets__history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_datasets_account_id_accounts"),
            "accounts",
            ["account_id"],
            ["account_id"],
        )
        batch_op.create_index(
            batch_op.f("ix_datasets__history_account_id"), ["account_id"], unique=False
        )

    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_datasets_account_id_accounts"),
            "accounts",
            ["account_id"],
            ["account_id"],
        )
        batch_op.create_index(batch_op.f("ix_datasets_account_id"), ["account_id"], unique=False)

    with op.batch_alter_table("scopes", schema=None) as batch_op:
        batch_op.alter_column(
            "scope",
            existing_type=sa.Enum(
                "submit",
                "upload",
                "review",
                "admin",
                "root",
                "edit",
                "permissions",
                "delete",
                name="scopes",
            ),
            type_=sa.VARCHAR(length=6),
            existing_nullable=False,
        )

    with op.batch_alter_table("item_scope_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_scope_links_scope_id"))
        batch_op.drop_index(batch_op.f("ix_item_scope_links_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_item_scope_links_account_id"))

    op.drop_table("item_scope_links")
    # ### end Alembic commands ###
